export const BaseUrl ='https://learnify.website'
export const TutorBaseUrl ='https://learnify.website/tutor'
export const UserBaseUrl ='https://learnify.website/student'
export const AdminBaseUrl ='https://learnify.website/admin'
export const PaymentBaseUrl = 'https://learnify.website/api/checkout'